modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dmz_addon"
version="1.0"
displayName="DMZAddon"
description="Small example for creating custom race/forms addons for DMZ."
authors="ezShokkoh"

[[dependencies.dmz_addon]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dmz_addon]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
